In [21]:
import numpy as np
from sympy import *

In [12]:
X = np.array([2, 5, 0, 6,8,10,6,7,5,7])
X1 = 3 * np.array([2, 5, 0, 6,8,10,6,7,5,7])
X1

array([ 6, 15,  0, 18, 24, 30, 18, 21, 15, 21])

In [8]:
Y = np.array([8,7,6,9,6,6,2,3,2,3])
Y1 = Y*2

In [9]:
Z = X1*Y1
Z

array([ 96, 210,   0, 324, 288, 360,  72, 126,  60, 126])

In [11]:
A = 6 * np.array([9,6,7,7,0,1,6,8,1,2]) * 5 * np.array([0,2,2,6,7,8,8,3,1,8])
A

array([   0,  360,  420, 1260,    0,  240, 1440,  720,   30,  480])

In [13]:
B = X * Y
B

array([16, 35,  0, 54, 48, 60, 12, 21, 10, 21])

In [14]:
C = np.array([9,6,7,7,0,1,6,8,1,2]) * np.array([0,2,2,6,7,8,8,3,1,8])
C

array([ 0, 12, 14, 42,  0,  8, 48, 24,  1, 16])

In [18]:
def transponirovanieMatrix(matrix):
    listTmp = []
    razm = matrix.shape
    for i in range(razm[1]):
        intListTmp = []
        for j in range(razm[0]):
            intListTmp.append(matrix[j][i])
        listTmp.append(intListTmp)
    return np.array(listTmp)

In [19]:
M = np.array([[2,1,7,4],[5,6,7,3],[9,8,2,12],[11,14,15,15]])
Mt = transponirovanieMatrix(M)
Mt

array([[ 2,  5,  9, 11],
       [ 1,  6,  8, 14],
       [ 7,  7,  2, 15],
       [ 4,  3, 12, 15]])

In [20]:
M2 = np.array([[3,7,8,3,6],[2,5,9,4,13]])
M2t = transponirovanieMatrix(M2)
M2t

array([[ 3,  2],
       [ 7,  5],
       [ 8,  9],
       [ 3,  4],
       [ 6, 13]])

In [23]:
a1, a2 = symbols('a1, a2')

MSE = 1 / 4 * ((1 * a1 + 2 * a2 - 5)**2 + \
               (5 * a1 + 3 * a2 - 6)**2 + \
               (2 * a1 + 4 * a2 - 10)**2 + \
               (3 * a1 + 7 * a2 - 8)**2)
MSE.subs({a1: 0.57, a2: 0.91})

8.56082500000000

In [24]:
MSEa1 = diff(MSE, a1)
MSEa1

19.5*a1 + 23.0*a2 - 39.5

In [25]:
MSEa2 = diff(MSE, a2)
MSEa2

23.0*a1 + 39.0*a2 - 62.0

In [26]:
step = 0.01

In [27]:
deltaA1 = MSEa1.subs({a1: 0.57, a2: 0.91})
deltaA1

-7.45500000000000

In [28]:
deltaA2 = MSEa2.subs({a1: 0.57, a2: 0.91})
deltaA2

-13.4000000000000

In [29]:
tochka = np.array([0.57, 0.91])
odMSE = -1* step* np.array([deltaA1, deltaA2])
odMSE

array([0.0745500000000000, 0.134000000000000], dtype=object)

In [30]:
tochka2 = tochka + odMSE
tochka2

array([0.644550000000000, 1.04400000000000], dtype=object)

In [31]:
MSE.subs({a1: tochka2[0], a2: tochka2[1]})

6.84354744937500

In [32]:
deltaA1 = MSEa1.subs({a1: tochka2[0], a2: tochka2[1]})
deltaA2 = MSEa2.subs({a1: tochka2[0], a2: tochka2[1]})
odMSE = -1* step* np.array([deltaA1, deltaA2])
odMSE

array([0.0291927500000000, 0.0645935000000000], dtype=object)

In [33]:
tochka3 = tochka2 + odMSE
tochka3

array([0.673742750000000, 1.10859350000000], dtype=object)

In [34]:
MSE.subs({a1: tochka3[0], a2: tochka3[1]})

6.47413334061399

In [35]:
deltaA1 = MSEa1.subs({a1: tochka3[0], a2: tochka3[1]})
deltaA2 = MSEa2.subs({a1: tochka3[0], a2: tochka3[1]})
odMSE = -1* step* np.array([deltaA1, deltaA2])
odMSE

array([0.00864365875000004, 0.0326877025000000], dtype=object)

In [36]:
tochka4 = tochka3 + odMSE
tochka4

array([0.682386408750000, 1.14128120250000], dtype=object)

In [38]:
MSE.subs({a1: tochka4[0], a2: tochka4[1]})

6.38787584353824

In [40]:
deltaA1 = MSEa1.subs({a1: tochka4[0], a2: tochka4[1]})
deltaA2 = MSEa2.subs({a1: tochka4[0], a2: tochka4[1]})
odMSE = -1* step* np.array([deltaA1, deltaA2])
odMSE

array([-0.000560026281250039, 0.0179514570124999], dtype=object)

In [41]:
tochka5 = tochka4 + odMSE
tochka5

array([0.681826382468750, 1.15923265951250], dtype=object)

In [43]:
MSE.subs({a1: tochka5[0], a2: tochka5[1]})

6.36167480075008

In [44]:
deltaA1 = MSEa1.subs({a1: tochka5[0], a2: tochka5[1]})
deltaA2 = MSEa2.subs({a1: tochka5[0], a2: tochka5[1]})
odMSE = -1* step* np.array([deltaA1, deltaA2])
odMSE

array([-0.00457965626928125, 0.0110791948223125], dtype=object)

In [45]:
tochka6 = tochka5 + odMSE
tochka6

array([0.677246726199469, 1.17031185433481], dtype=object)

In [46]:
MSE.subs({a1: tochka6[0], a2: tochka6[1]})

6.34873371109374