In [ ]:
from sympy import *

In [ ]:
a1, a2 = symbols('a1, a2')

MSE = 1 / 4 * ((1 * a1 + 2 * a2 - 5)**2 + \
               (5 * a1 + 3 * a2 - 6)**2 + \
               (2 * a1 + 4 * a2 - 10)**2 + \
               (3 * a1 + 7 * a2 - 8)**2)
MSE.subs({a1: 0.57, a2: 0.91})

8.56082500000000

In [ ]:
MSEa1 = diff(MSE, a1)
MSEa1

19.5*a1 + 23.0*a2 - 39.5

In [ ]:
MSEa2 = diff(MSE, a2)
MSEa2

23.0*a1 + 39.0*a2 - 62.0

In [ ]:
step = 0.01

In [ ]:
[1, 3] - [2, 1]

In [ ]:
import numpy

In [ ]:
numpy.array([1, 3]) - numpy.array([2, 1])

array([-1,  2])

In [ ]:
# point = numpy.array([0.57, 0.91])
point = next_point

In [ ]:
grad = numpy.array([MSEa1.subs({a1: point[0], a2: point[1]}),
                    MSEa2.subs({a1: point[0], a2: point[1]})])
grad

array([0.457965626928125, -1.10791948223125], dtype=object)

In [ ]:
next_point = point - step * grad
next_point

array([0.677246726199469, 1.17031185433481], dtype=object)

In [ ]:
MSE.subs({a1: next_point[0], a2: next_point[1]})

6.34873371109374