In [1]:
import numpy as np
from sympy import *

In [13]:
x, y, z = symbols('x, y, z')
a, b = symbols('a, b')
x1, x2, x3 = symbols('x1, x2, x3')

In [3]:
eq1 = -1*x + 7*y + 4
eq2 = 8*x + 8*y + 48
linsolve([eq1, eq2], [x,y])

{(-19/4, -5/4)}

In [4]:
eq1 = 4*x - 7*y + 4
eq2 = 3*x - 4*y + 3
linsolve([eq1, eq2], [x,y])

{(-1, 0)}

In [6]:
eq1 = 8*a - 4*b - 64
eq2 = -3*a + 3*b + 21
linsolve([eq1, eq2], [a,b])

{(9, 2)}

In [7]:
eq1 = 5*x1 + 7*x2 - 5*x3 + 47
eq2 = -2*x2 + 2*x3 - 10
eq3 = -4*x1 - 8*x2 - 7 * x3 - 63
linsolve([eq1, eq2, eq3], [x1,x2,x3])

{(-2, -6, -1)}

In [9]:
A = Matrix([[-1, 7], [8, 8]])
B = Matrix([-1, -5])
A*B

Matrix([
[-34],
[-48]])

In [10]:
A = Matrix([[4, -7], [3, -4]])
B = Matrix([-1, 0])
A*B

Matrix([
[-4],
[-3]])

In [11]:
A = Matrix([[8, -4], [-3, 3]])
B = Matrix([9, 2])
A*B

Matrix([
[ 64],
[-21]])

In [12]:
A = Matrix([[5, 7, -5], [0, -2, 2], [-4, -8, -7]])
B = Matrix([-2, -6, -1])
A*B

Matrix([
[-47],
[ 10],
[ 63]])

In [18]:
MSE = 1/6 * ((5*x + 7*y -5*z + 47)**2 + \
             (-2*y + 2*z - 10)**2 + \
             (-4*x -8*y -7*z - 63)**2 + \
             (x + y + 2*z + 1)**2 + \
             (2*x - y + 2*z + 4)**2 + \
             (4*x + y + 4*z + 2)**2)

MSE.subs({x:0, y:0, z:0})

1049.83333333333

In [20]:
MSEx = diff(MSE, x)
MSEy = diff(MSE, y)
MSEz = diff(MSE, z)
step = 0.01

In [21]:
tochka = np.array([0, 0, 0])
while MSE.subs({x: tochka[0], y: tochka[1], z: tochka[2]}) > 55:
    obj = {x: tochka[0], y: tochka[1], z: tochka[2]}
    odMSE = -1*step*np.array([MSEx.subs(obj), MSEy.subs(obj), MSEz.subs(obj)])
    tochka = tochka + odMSE
    print(tochka)
    print(MSE.subs({x: tochka[0], y: tochka[1], z: tochka[2]}))

[-1.68000000000000 -2.84000000000000 -0.680000000000000]
247.497333333333
[-2.29346666666667 -4.10440000000000 -0.790000000000000]
104.486005072593
[-2.47595688888889 -4.71219777777778 -0.722969777777778]
73.7744351503798
[-2.48449883555556 -5.03898750814815 -0.620976468148148]
64.1857120851198
[-2.42352395196049 -5.24020775715556 -0.530073773777778]
59.5591801838142
[-2.33577437740421 -5.38153056800477 -0.461073818362404]
56.5686545495930
[-2.23893438867603 -5.49162915212318 -0.412953715575168]
54.3188045027199
